name: CI (checks) & Netlify deploy

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: ci-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build & quick checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Syntax check (JS/ESM/CJS)
        run: |
          files="$(git ls-files '**/*.mjs' '**/*.cjs' '**/*.js' || true)"
          if [ -n "$files" ]; then
            echo "$files" | xargs -r -n1 node --check
          fi

      - name: Bundle sanity (window-log)
        run: npx esbuild netlify/functions/window-log.mjs --bundle --platform=node --format=cjs --outfile=/tmp/window-log.cjs

  deploy:
    name: Netlify deploy (main only)
    needs: build
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && secrets.NETLIFY_AUTH_TOKEN && secrets.NETLIFY_SITE_ID }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
      - run: npm ci
      - name: Netlify CLI deploy (prod)
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID:    ${{ secrets.NETLIFY_SITE_ID }}
        run: npx netlify deploy --build --prod --message "CI $GITHUB_SHA"
