name: enrich-ci
on:
  pull_request:
    paths:
      - 'netlify/functions/run-picks-scan-markets.cjs'
      - 'netlify/functions/__tests__/**'
      - 'package-lock.json'
      - 'package.json'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '22' }
      - run: npm ci
      - run: npm test --silent
