name: Netlify Auto Deploy (con chequeo de sintaxis)

on:
  push:
    branches: [ "main" ]
    paths:
      - "netlify/functions/**"
      - "netlify.toml"
      - ".github/workflows/netlify-auto-deploy.yml"
  workflow_dispatch:

jobs:
  check-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Syntax check (serverless functions)
        shell: bash
        run: |
          set -e
          echo "Node version:"
          node -v
          echo "Archivos a checar:"
          for f in $(ls -1 netlify/functions/*.{js,cjs} 2>/dev/null || true); do
            echo "→ Checando $f"
            node --check "$f"
          done

      - name: Trigger Netlify Build Hook
        env:
          NETLIFY_BUILD_HOOK: ${{ secrets.NETLIFY_BUILD_HOOK }}
        run: |
          if [ -z "$NETLIFY_BUILD_HOOK" ]; then
            echo "ERROR: Falta el secret NETLIFY_BUILD_HOOK en GitHub → Settings > Secrets and variables > Actions."
            exit 1
          fi
          echo "Llamando hook de Netlify…"
          curl -sS -X POST -H "Content-Type: application/json" -d '{}' "$NETLIFY_BUILD_HOOK"
          echo "Hook enviado."
