name: Netlify Auto Deploy (con chequeo de sintaxis)

on:
  push:
    branches: [ "main" ]
    paths:
      - "netlify/functions/**"
      - "netlify.toml"
      - ".github/workflows/netlify-auto-deploy.yml"
  workflow_dispatch:

jobs:
  check-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Chequeo de sintaxis: recorre *.js y *.cjs en netlify/functions
      - name: Syntax check (serverless functions)
        shell: bash
        run: |
          set -e
          echo "Node version:"
          node --version
          echo "Archivos a checar:"
          files=$(ls netlify/functions/*.js netlify/functions/*.cjs 2>/dev/null || true)
          if [ -z "$files" ]; then
            echo "No hay archivos .js/.cjs en netlify/functions; continúo."
          else
            for f in $files; do
              echo "→ Checando $f"
              node --check "$f"
            done
          fi

      # Si pasó el check, dispara el Build Hook de Netlify
      - name: Trigger Netlify Build Hook
        env:
          NETLIFY_BUILD_HOOK: ${{ secrets.NETLIFY_BUILD_HOOK }}
        run: |
          if [ -z "$NETLIFY_BUILD_HOOK" ]; then
            echo "ERROR: Falta el secret NETLIFY_BUILD_HOOK en GitHub → Settings > Secrets and variables > Actions."
            exit 1
          fi
          echo "Llamando hook de Netlify…"
          curl -sS -X POST -H "Content-Type: application/json" -d '{}' "$NETLIFY_BUILD_HOOK"
          echo "Hook enviado."
