name: Check Syntax

on:
  push:
    branches: [ "main" ]
    paths:
      - "netlify/functions/**"
      - "netlify.toml"
      - ".github/workflows/netlify-auto-deploy.yml"
      - "package.json"
      - "package-lock.json"
  workflow_dispatch:

jobs:
  check-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Syntax check (serverless functions)
        shell: bash
        run: |
          set -e
          echo "Node version:"
          node -v
          echo "Archivos a checar:"
          for f in $(ls -1 netlify/functions/*.{js,cjs} 2>/dev/null || true); do
            echo "→ Checando $f"
            node --check "$f"
          done

      # (opcional) si tienes build local, descomenta:
      # - name: Install & Build
      #   run: |
      #     npm ci
      #     npm run build

      - name: Deploy to Netlify (prod)
        if: github.ref == 'refs/heads/main'
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: .                          # igual que publish="." en netlify.toml
          production-deploy: true
          deploy-message: "Deploy ${{ github.sha }} 🚀"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          enable-commit-comment: true
          enable-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
