name: Smoke Functions v2
on:
  workflow_dispatch:
permissions:
  contents: read
  actions: write
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Echo ok
        shell: bash
        run: echo "[AF_DEBUG] v2 reindexed"
