name: Smoke Repo Secrets
on: { workflow_dispatch: {} }
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Measure repo-level secrets
        shell: bash
        run: |
          set -euo pipefail
          sb_b=$(printf '%s' "${{ secrets.SITE_BASE }}" | wc -c)
          dt_b=$(printf '%s' "${{ secrets.DEBUG_TOKEN }}" | wc -c)
          ct_b=$(printf '%s' "${{ secrets.ECHO_TEST }}" | wc -c)
          echo "[AF_DEBUG] INLINE SITE_BASE bytes=$sb_b"
          echo "[AF_DEBUG] INLINE DEBUG_TOKEN bytes=$dt_b"
          echo "[AF_DEBUG] INLINE ECHO_TEST bytes=$ct_b"
