name: Smoke Functions v3
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Echo ok
        shell: bash
        run: echo "[AF_DEBUG] v3 alive"
