name: Smoke Functions

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  actions: write

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      SITE_BASE: ${{ secrets.SITE_BASE }}
      DEBUG_TOKEN: ${{ secrets.DEBUG_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Show context (raw vs trim) + export
        shell: bash
        run: |
          set -euo pipefail
          SB_RAW="${SITE_BASE:-}"
          DT_RAW="${DEBUG_TOKEN:-}"
          SB_TRIM="$(printf "%s" "$SB_RAW" | tr -d '\r\n')"
          DT_TRIM="$(printf "%s" "$DT_RAW" | tr -d '\r\n')"

          echo "[AF_DEBUG] SITE_BASE raw len=${#SB_RAW}  trim len=${#SB_TRIM}"
          echo "[AF_DEBUG] DEBUG_TOKEN raw len=${#DT_RAW} trim len=${#DT_TRIM}"

          if [ -z "$SB_TRIM" ] || [ -z "$DT_TRIM" ]; then
            echo "::error::Secrets vacíos (tras trim). Revisa SITE_BASE/DEBUG_TOKEN"
            exit 1
          fi

          {
            echo "SB_TRIM=$SB_TRIM"
            echo "DT_TRIM=$DT_TRIM"
          } >> "$GITHUB_ENV"
      - name: Install jq & curl
        shell: bash
        run: |
          set -euo pipefail
          sudo apt-get update -y
          sudo apt-get install -y jq curl

      - name: Smoke (diag-impl-call + autopick-vip-run3)
        shell: bash
        run: |
          set -euo pipefail
          BASE="$SB_TRIM"
          TKN="$DT_TRIM"
          echo "[AF_DEBUG] BASE=$BASE"
          echo "[AF_DEBUG] DEBUG_TOKEN len (trim) = ${#TKN}"

          pass=1

          smoke_fn () {
            local fn="$1"

            # inspect -> 200 + hasHandler==true
            local code
            code=$(curl -sS -o "/tmp/${fn}_i.json" -w '%{http_code}' \
              "$BASE/$fn?inspect=1&debug=1" \
              -H "x-debug: 1" -H "x-debug-token: $TKN")
            if [ "$code" = "200" ] && jq -e '.hasHandler==true' </tmp/"${fn}"_i.json >/dev/null 2>&1; then
              echo "[AF_DEBUG] $fn inspect OK (200)"
            else
              echo "[AF_DEBUG] $fn inspect FAIL (code=$code)"; pass=0
              jq . "/tmp/${fn}_i.json" 2>/dev/null || cat "/tmp/${fn}_i.json" || true
            fi
            # bypass -> 403
            code=$(curl -sS -o "/tmp/${fn}_b.json" -w '%{http_code}' \
              "$BASE/$fn?bypass=1&debug=1" \
              -H "x-debug: 1" -H "x-debug-token: $TKN")
            if [ "$code" = "403" ]; then
              echo "[AF_DEBUG] $fn bypass OK (403)"
            else
              echo "[AF_DEBUG] $fn bypass FAIL (code=$code)"; pass=0
              jq . "/tmp/${fn}_b.json" 2>/dev/null || cat "/tmp/${fn}_b.json" || true
            fi
          }

          smoke_fn "diag-impl-call"
          smoke_fn "autopick-vip-run3"

          if [ "$pass" = "1" ]; then
            echo "[AF_DEBUG] SMOKE OK"
          else
            echo "::error::SMOKE FAILED"
            exit 1
          fi
