name: Smoke Functions v5
on:
  workflow_dispatch:
permissions:
  contents: read
  actions: write

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show context (raw vs trim)
        continue-on-error: true
        shell: bash
        env:
          SITE_BASE: ${{ secrets.SITE_BASE }}
          DEBUG_TOKEN: ${{ secrets.DEBUG_TOKEN }}
        run: |
          set -euo pipefail
          SB_RAW="${SITE_BASE:-}"
          DT_RAW="${DEBUG_TOKEN:-}"
          SB_TRIM="$(printf "%s" "$SB_RAW" | tr -d '\r\n')"
          DT_TRIM="$(printf "%s" "$DT_RAW" | tr -d '\r\n')"
          echo "[AF_DEBUG] SITE_BASE raw len=${#SB_RAW}  trim len=${#SB_TRIM}"
          echo "[AF_DEBUG] DEBUG_TOKEN raw len=${#DT_RAW} trim len=${#DT_TRIM}"
          echo "[AF_DEBUG] SITE_BASE bytes=$(printf '%s' "$SB_TRIM" | wc -c)"
          echo "[AF_DEBUG] DEBUG_TOKEN bytes=$(printf '%s' "$DT_TRIM" | wc -c)"
          echo "::warning::Este step es solo diagnóstico; no debe bloquear"

      - name: Measure via step env
        shell: bash
        env:
          SB: ${{ secrets.SITE_BASE }}
          DT: ${{ secrets.DEBUG_TOKEN }}
        run: |
          set -euo pipefail
          sbb=$(printf '%s' "$SB" | wc -c)
          dtb=$(printf '%s' "$DT" | wc -c)
          echo "[AF_DEBUG] STEP_ENV SITE_BASE bytes=$sbb"
          echo "[AF_DEBUG] STEP_ENV DEBUG_TOKEN bytes=$dtb"
          if [ "$sbb" -lt 10 ] || [ "$dtb" -lt 8 ]; then
            echo "::error::step-env looks short (SB=$sbb, DT=$dtb)"; exit 1
          fi

      - name: Measure via inline expression (no job env)
        shell: bash
        run: |
          set -euo pipefail
          SBB=$(printf '%s' "${{ secrets.SITE_BASE }}" | wc -c)
          DTB=$(printf '%s' "${{ secrets.DEBUG_TOKEN }}" | wc -c)
          echo "[AF_DEBUG] INLINE SITE_BASE bytes=$SBB"
          echo "[AF_DEBUG] INLINE DEBUG_TOKEN bytes=$DTB"
          if [ "$SBB" -lt 10 ] || [ "$DTB" -lt 8 ]; then
            echo "::error::inline looks short (SB=$SBB, DT=$DTB)"; exit 1
          fi
